version: '3'

services:
  mcs:
    image: mcs-image
    ports:
      - "8082:8082"
    depends_on:
      - satellite
      - satellite
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/mcsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  satellite:
    image: satellite-image
    ports:
      - "8083:8083"

  satellite-api:
    build:
      context: ./path/to/satellite
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - satellite

  postgres:
    image: postgres:14.3-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@takehome.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - postgres
